export const GET_MEDICAL_RECORDS = "GET_MEDICAL_RECORDS";
export const REMOVE_PATIENT_RECORD = "REMOVE_PATIENT_RECORD";
export const REMOVE_PATIENTS_RECORDS_BY_GROUP =  "REMOVE_PATIENTS_RECORDS_BY_GROUP";
export const ADD_LOGIN_USER  =  "ADD_LOGIN_USER";
